### ISSUE TITLE
Add ability to sort by dataset name / date / creator username / size

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-lookup-webapp#1]
This will make it easier to find datasets of interest.

It is likely that the natural place this functionality will be somewhere just below the header.

**Comment by jotelha** [comment]
With pagination implemented on the server side, sorting would have to happen on the server side as well. Maybe implementing a standardized sorting decorator in the same fashion as the `flask_smorest.Blueprint.paginate` decorator https://flask-smorest.readthedocs.io/en/latest/api_reference.html#flask_smorest.Blueprint.paginate in the server might be a good idea to make a route like https://github.com/jic-dtool/dtool-lookup-server/blob/d7c5fc1c26c5641e00c346f89c086adce46e3d44/dtool_lookup_server/dataset_routes.py#L101-L118 look like this
```python
@bp.route("/search", methods=["POST"])
@bp.arguments(SearchDatasetSchema(partial=True))
@bp.response(200, DatasetSchema(many=True))
@bp.sort()
@bp.paginate()
@jwt_required()
def search_datasets(
    query: SearchDatasetSchema, pagination_parameters: PaginationParameters, sort_parameters: SortParameters
):
    """List datasets the user has access to matching the query."""
    username = get_jwt_identity()
    try:
        datasets = search_datasets_by_user(username, query, sort_parameters) 
        # better delegate sorting to DB here ...
    except AuthenticationError:
        abort(401)
    # ... or apply sorting post-query here 
    pagination_parameters.item_count = len(datasets)
    return jsonify(
        datasets[pagination_parameters.first_item : pagination_parameters.last_item + 1]
    )
```
with `sort_parameters` providing a list of (key, direction) pairs, like for https://pymongo.readthedocs.io/en/stable/api/pymongo/cursor.html#pymongo.cursor.Cursor.sort .

**Comment by jotelha** [comment]
Addressed within https://github.com/jic-dtool/dtool-lookup-webapp/pull/30
