### ISSUE TITLE
Add pagination when there are more than 50 datasets in the DataSetTable view

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-lookup-webapp#8]
This will probably requires some improvements to the dtool-lookup-server

**Comment by jotelha** [comment]
We started working on pagination in the webapp here, https://github.com/livMatS/dtool-lookup-webapp/pull/65, Ashwin (https://github.com/ashdriod) started as a research assistant with me in mid January and is initially tasked with polishing this demonstrator webapp. Will keep you updated.

**Comment by jotelha** [comment]
Addressed within https://github.com/jic-dtool/dtool-lookup-webapp/pull/30
